### ISSUE TITLE
DVMRP reporting missing last subnet that should be listed in report

### ISSUE THREAD

**Issue by matthew-l-weber** [troglobit/mrouted#14]
Based on some testing where we added a list of subnets to the DVMRP report coming from host A, it was determined that mrouted on host B (A and B are connected with a L2 switch) was always missing the last subnet reported in the DVMRP report. Some of the debug output from mrouted as well as its route dump was showing that it was processing this subnet, but wasn't transmitting it within the DVMRP report nor was it processing traffic originating from this subnet.

Reverting back to the 3.9-beta3 version of mrouted resolved this issue, while version 3.9.7 was the one exhibiting this behavior. Beyond that we haven't investigation as to where along the line the bug may have been introduced.

We are running a 3.12.19 Linux kernel.

**Comment by troglobit** [comment]
Thanks for the report!  Sounds like an off-by-one bug has been introduced somewhere.

Do you plan to do some further investigation into this, e.g. narrowing down the release the bug appeared in?

**Comment by matthew-l-weber** [comment]
Yeah, hoping to investigate later this week.

**Comment by troglobit** [comment]
Thx! :smiley:

**Comment by matthew-l-weber** [comment]
Found the fix and submitted https://github.com/troglobit/mrouted/pull/15

**Comment by troglobit** [comment]
Merged PR #15, closing. Thanks again!
