### ISSUE TITLE
Building fails on Arch x86_64, fix attached

### ISSUE THREAD

**Issue by jefbed** [troglobit/mrouted#17]
GCC/glibc warns that _BSD_SOURCE is deprecated, to use _DEFAULT_SOURCE instead.
In mapper.c, line 490, it looks like a typo-- a variable is compared to itself.  Changed rvalue to nb_n->threshold.

[mrouted_linux.txt](https://github.com/troglobit/mrouted/files/546791/mrouted_linux.txt)

**Comment by troglobit** [comment]
Hi,

thanks for the patch, but too late. These fixes have already made it to the sources (some time ago
actually). When submitting fixes, in particular on GitHub, please do so against the latest GIT master
and preferably as a pull request.

Cheers

**Comment by jefbed** [comment]
Thank you for the pointer, will do.  I let the Arch AUR maintainer for the package know about the build error, so hopefully it will be fixed downstream.
