### ISSUE TITLE
10 seconds to establish routes?

### ISSUE THREAD

**Issue by Bischoff** [troglobit/mrouted#18]
Hello,

I have played with mrouted and noticed that I needed to wait at least 10 seconds to see the multicast routes appear on the router in this very simple setup:

       host ---- router ---- host

Both hosts request to join same multicast group. If I replace mrouted with smcroute, multicasting works immediately. I tested mrouted 3.9.6 as packaged 5 years ago (yep).

In the RFC 1075, one can read:

      Probes provide a keep-alive function in order to quickly detect
      neighbor loss. Probes sent on each multicast capable interface
      configured for DVMRP SHOULD use an interval of 10 seconds.

However, 10 seconds between probes does not mean IMHO that it is needed to wait 10 seconds to register a route based on a first IGMP join message. Is it an implementation problem of mrouted?

Or did I miss some point? Do other people experience this 10 seconds delay as well?

Best,

**Comment by troglobit** [comment]
Try v3.9.7, or the latest master, but I wouldn't be at all surprised that it takes 10 sec for good 'ol mrouted to set the routes.

It could be some overzealous interpretation of IGMP (10 sec is usually the default response time to a query), or simply optimized to reduce the amount of disruptions to established streams. 

You can't really compare it to SMCRoute since that is completely "off-line scheduled" and knows beforehand what routes to tell the kernel to set.

**Comment by Bischoff** [comment]
I tested with latest master (3.9.8-rc1)

I think the guilty code is the following, in file main.c:

    /* XXX HACK
     * This will cause black holes for the first few seconds after startup,
     * since we are exchanging routes but not actually forwarding.
     * However, it eliminates much of the startup transient.
     *
     * It's possible that we can set a flag which says not to report any
     * routes (just accept reports) until this timer fires, and then
     * do a report_to_all_neighbors(ALL_ROUTES) immediately before
     * turning on DVMRP.
     */
    timer_setTimer(10, final_init, NULL);

Any hope to control this through a flag like --wait 10 ?

**Comment by Bischoff** [comment]
Or document the behaviour...

**Comment by troglobit** [comment]
I'm more than willing to merge patches or pull requests with said functionality or doc updates :smirk: 

As a side note, I've sort of been planning to migrate to a proper configure script, using autoconf+automake, but mrouted haven't been at the top of my radar for a while now,
unfortunately.

I think a `--enable-startup-delay=SEC`, which defaults to enabled=10, and is possible to
`--disable-startup-delay` would be a neat feature to have.  But as I said, right now mrouted
is not my top priority, but if you develop and test the feature I can easily spare the time to
merge the pull request here.

**Comment by Bischoff** [comment]
Sure.

By the way, thank you for maintaining smcroute, mrouted, and pimd.

**Comment by Bischoff** [comment]
Pull request submitted. Feel free to close this issue once you accepted or refused it.

**Comment by troglobit** [comment]
Looks awesome, thanks! :+1:

**Comment by Bischoff** [comment]
Cool, your latest commit to get rid of string constant. Why did I miss that ? :-)
