### ISSUE TITLE
mrouted sends malformed IGMPV3 general query request

### ISSUE THREAD

**Issue by borisu** [troglobit/mrouted#30]
I am trying to use mrouted in CORE network simulator. I have built it form latest sources. However I have noticed that it sends malformed IGMP packets as general IGMP queries which cannot be  parsed by any version of Wireshark.

Example is 01005e000001000000aa0015080045c00020075a00000102bdbf0a000a02e00000011164f41300000000fa7d000a

**Comment by troglobit** [comment]
Works fine here, but the last four bytes in your dump there look a bit weird, they encode the robustness and query interval.  Would you mind adding the contents of your `.conf` file to the mix?

**Comment by troglobit** [comment]
I've just pushed d1c4ceb as a possible mitigation, it just cleans the send buffer before composing an IGMP message. Might help ...

**Comment by troglobit** [comment]
Bad ideas always tend to surface when it's too late at night; d1c4ceb broke sending completely, reverting.

**Comment by borisu** [comment]
[I believe it made it worse now I see packets like that :-

01005e000004000000aa001608000000002000000000010000000a000b01e00000041301edec000eff0300000000


However it may tell us where the problem is.

The mrouted.conf is almost default (see at the end) . I reduced IGMP timer to 15 to not wait to see the packets.

One small change (and also issue in mrouted) I think you should be aware of :-

Firstly the issue is that in case mrouted cannot open the ipc socket it will still add it to monitored descriptor. Then poll function will fail immediately causing the mrouted to conusme the CPU but still be able to respond to IGMP requests. In case of CORE simulator it happened  because there was a collision between file namespaces of simulated processes. In order to run properly in simulator I had to slightly change the generated makefile so it will remap the  DRUNSTATEDIR macro. I cannot imagine how it can affect mrouted  but still informing you on that. BTW for some reason RUNSTATEDIR is not part of configure variables set which is why I had to change in generated file from the beginning.

AM_CPPFLAGS = -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_GNU_SOURCE \
  4         -I$(top_srcdir)/include -DSYSCONFDIR=\"${prefix}/etc\" \
  5         -DRUNSTATEDIR=\"/var/mrouted\" \
  6         -DPRESERVEDIR=\"/var/mrouted\" $(am__append_1)


I am running in vmware ubuntu trusty ](url)
[config.log](https://github.com/troglobit/mrouted/files/3052752/config.log)

**Comment by troglobit** [comment]
OK, one issue at a time. I've reverted the first fix I did, my current theory is that the frame is too short, so I've padded it up to min frame size in b189c27.

I'll look into the issue with the IPC socket.  It's a bit worrying to hear about the file namespace issue in  CORE you mention. I also use CORE and haven't really seen any such issues, maybe because I run their latest GitHub release, I don't know.  In `pimd` (another project I maintain), I've added support for running multiple instances. I haven't gotten around to that in mrouted.

**Comment by troglobit** [comment]
Fixed IPC issue in 8e51918, thanks!

**Comment by troglobit** [comment]
I've tested this back and forth now, even on actual hardware, and I cannot find anything wrong.  If anything, the recent patches made it worse, so I've reverted them both.  The driver pads to min Ethernet packet size.

It would be really great if you could attach an actual Wireshark/tcpdump pcap file  to this issue, otherwise I will not be able to debug this further.

**Comment by borisu** [comment]
I will. can you please guide me on where to debug so I can help from my side?

The Ipc issue was relatively easy but this one I need your guidance o where to look.

**Comment by troglobit** [comment]
To create a pcap file you can use the following command from the other end of the connection where mrouted runs:

```
tcpdump -s 1500 -lni eth0 -w dump.pcap
```

Let's start with that and we can take it from there.

**Comment by borisu** [comment]
Yep that would not be a problem. I meant the actual line in code where to put breakpoint and look for some problematic data.

**Comment by troglobit** [comment]
Sure, the code in src/igmp.c (at the very bottom) handles composition and send of IGMP frames.  See the functions `build_query()` and `send_igmp()`.  However, I'm not convinced yet there is a problem with the code.

**Comment by troglobit** [comment]
Any progress on that pcap?  I'm really curious about this!

**Comment by borisu** [comment]
I had some difficulty getting to the computer. You can feed the byte stream above to http://packetor.com/ and see the structure. From what I can tell you,the problem seams to be the number of sources field which includes some random numbers. In the byte stream above it is 10 though from my understanding for general query it should be 0. From code I cannot see where it is being initiated. build_query function seams to initiate everything but it, and send_buf is reused without clean up as far as I see. 

I would expect something like igmp->nsrcs = 0 at the end of the build_query function. Does it make sense to you?

**Comment by troglobit** [comment]
Yup, that makes a lot of sense. Thank you for sticking with this and helping solve a nasty bug! 

I believe the following patch, which I'll push soon, is slightly more complete:

```diff
@@ -468,7 +480,9 @@ size_t build_query(uint32_t src, uint32_t dst, int type, int code, uint32_t grou
     else
        ip->ip_ttl    = MAXTTL;
 
-    igmp              = (struct igmpv3_query *)(send_buf + MIN_IP_HEADER_LEN);
+    igmp = (struct igmpv3_query *)(send_buf + IP_RA_HEADER_LEN);
+    memset(igmp, 0, sizeof(*igmp));
+
     igmp->type        = type;
     if (datalen >= 4)
         igmp->code    = igmp_floating_point(code);
```
