### ISSUE TITLE
Problems with mrouted on Linux?

### ISSUE THREAD

**Issue by troglobit** [troglobit/mrouted#4]
Investigate this claim http://www.keyongtech.com/4493327-mrouted-and-igmp-on-linux

**Comment by Bischoff** [comment]
Original pointer seems dead. Here is a new one:

    http://www.textndata.com/forums/mrouted-igmp-linux-102561.html

**Comment by troglobit** [comment]
Latest pointer to the original post now seems to be https://www.network-builders.com/threads/mrouted-and-igmp-on-linux.48959/

However, I cannot replicate any issues with this.  My guess is that this was either fixed after 3.9.4, or that my IP-in-IP tunnel¹ setup is what solves the issue.  Its use wasn't mentioned in either the forum post or here by @sbrobson so maybe it was a simple case of an oversight.

My test setup uses three routers in one line, the middle one is used to simulate the Internet or an intranet.  The outermost routers have two hosts, one on each side, one sender and one receiver:

     H1 -----> R1 ------> R2 ------> R3 -----> H2

Only R1 and R3 run mrouted.  All routers do however run OSPF, but that's just to get unicast working so I can verify the topology with ping.  With DVMRP we have a sort-of stripped down RIP included, so mrouted is stand-alone in that regard (compared to PIM which requires an underlying unicast routing protocol first).

Nothing in the above setup works until I add a tunnel config to mroute.conf on R1 and R3, sort of like this:

    R1: mrouted.conf
    tunnel 10.0.0.1 10.0.2.1 metric 1 threshold 1 rate_limit 0
    
    R2: mrouted.conf
    tunnel 10.0.2.1 10.0.0.1 metric 1 threshold 1 rate_limit 0

The tunnel gets its own VIF in mrouted and routes are established as soon as H2 sends an IGMP join for the given multicasdt group I transmit as plain UDP from H1.

Sure, I have no firewall in place, this is plain routing, but I'm pretty confident the issue here was the lack of the IP-in-IP tunnel, which is documented in the man page.

(closing issue)
___
¹ built-in feature if enabled with tunnel directive in mrouted.conf
