### ISSUE TITLE
won't start as soon as I add a tunnel config?

### ISSUE THREAD

**Issue by ericb-summit** [troglobit/mrouted#52]
I have 3 mcast enabled interfaces on my system; eth0, eth1, and for sake of accuracy, docker0 (I do not intend to use docker0 for anything).

```
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
...
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 10.0.200.77  netmask 255.255.255.224  broadcast 10.0.200.95
...
eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 10.0.204.68  netmask 255.255.255.224  broadcast 10.0.204.95
```

When I run with no config, it starts as expected

```
mrouted    | 06:25:17.595 mrouted version 4.3 starting
...
mrouted    | 06:22:00.864 Installing eth0 (10.0.200.77 on subnet 10.0.200.64/27) as VIF #0, rate 0 pps
mrouted    | 06:22:00.864 Installing eth1 (10.0.204.68 on subnet 10.0.204.64/27) as VIF #1, rate 0 pps
mrouted    | 06:22:00.864 Installing docker0 (172.17.0.1 on subnet 172.17/16) as VIF #2, rate 0 pps
```

As I am attempting to use mrouted to tunnel multicast between two networks where the routers can speak to each other unicast but not multicast, I add a tunnel statement.  The config is completely empty except for this one line:

`tunnel 10.0.204.68 10.0.204.119 metric 1 threshold 1 rate-limit 0`

I run it, I see this:

```
mrouted    | 06:24:33.022 installing tunnel from 10.0.204.68 to 10.0.204.119 as vif #0 - rate=0
mrouted    | 06:24:33.022 Correlating interfaces and configuration ...
mrouted    | 06:24:33.022 Installing eth0 (10.0.200.77 on subnet 10.0.200.64/27) as VIF #0, rate 0 pps
mrouted    | 06:24:33.022 Installing eth1 (10.0.204.68 on subnet 10.0.204.64/27) as VIF #0, rate 0 pps
mrouted    | 06:24:33.022 Installing docker0 (172.17.0.1 on subnet 172.17/16) as VIF #0, rate 0 pps
mrouted    | 06:24:33.022 Installing eth1 (10.0.204.68 on subnet default) as VIF #0, rate 0 pps
mrouted    | 06:24:33.022 Cannot forward: no enabled vifs
```

And it exits.

To be sure it wasn't something wonky with my binary, I rebuilt 4.3 from scratch inside alpine latest per your instructions.  Then I tried debian stretch, then I dropped docker and just built in a AMI linux 2 instance.  Same exact behaviour.  My next step is to mark up the code to try to undertstand what is going on.

In the meantime, could you kindly comment if am I doing something very obviously wrong?  Why do I see VIF#0 repeatedly?  Why would installing the interface fail silently?  Thanks.

**Comment by troglobit** [comment]
Closing, v4.4 was just released with fixes for this issue.   Remaining work, to solve the actual use-case detailed here, is tracked in #54.

Thank you @ericb-summit for reporting this and helping out resolving it!

**Comment by ericb-summit** [comment]
> Closing, v4.4 was just released with fixes for this issue. Remaining work, to solve the actual use-case detailed here, is tracked in #54.
> 
> Thank you @ericb-summit for reporting this and helping out resolving it!

Thank you for the support
