### ISSUE TITLE
"Required key not available" on Arch Linux

### ISSUE THREAD

**Issue by DUOLabs333** [troglobit/mrouted#55]
I built `mrouted` 4.4 from release. I run it with `sudo ./mrouted -n`, and I periodically get `warning - sendto to 224.0.0.4 on 10.200.200.1: Required key not available`, `10.200.200.1` being the IP address of my Wireguard interface.

**Comment by DUOLabs333** [comment]
I added `224.0.0.0/24` to `AllowedIPs`, but now I get `Cannot forward: only one enabled vif`

**Comment by troglobit** [comment]
`mrouted` is for routing IPv4 multicast (outside of the 224.0.0.x range) between two or more interfaces.  Maybe I can help you better if you tell me a bit about your use-case, the mrouted.conf you are using and what you expected?

**Comment by DUOLabs333** [comment]
I'm not using any conf file,  and I want to route mDNS queries through Wireguard.

**Comment by troglobit** [comment]
OK, so you want to set up routing between all interfaces (that support multicast) on your system.  However, and as I suspected, you want to route link-local-only multicast ... this is a very common misconception wrt multicast routing.  mDNS lives in the reserved 224.0.0.0/24 range, specifically 224.0.0.25, which is reserved for link-local protocols such as IGMP, PIM, DVMRP, RIP, OSPF, ... and mDNS.  Most standards-compliant mDNS responders also transmit their frames with a TTL=1, another sign that it's never supposed to be routed.

In any case, mrouted is probably not for you, sorry.
