### ISSUE TITLE
Support reloading config file without flushing routing table

### ISSUE THREAD

**Issue by jemins** [troglobit/mrouted#6]
How can I reread the configuration file of Mrouted mrouted.conf without restarting the whole daemon and losing the routing tables. What should be the modifications in package for that.

I want it (daemon) should reread the config file and update according to new configurations but it should not flush the routing tables.

**Comment by troglobit** [comment]
I've looked into this some more over the years, and now in particular for the upcoming v4.0 release.  

Adding support for not interrupting established flows on `SIGHUP` (or `mroutectl restart`) is an incredibly complex job and very unlikely someone will ever fix in mrouted.  

Therefore I've decided to close this, for now.  No point in having open issues we never intend to fix.
