### ISSUE TITLE
Debian 12: 20:06:55.221 Another multicast routing application is already running

### ISSUE THREAD

**Issue by lucdig** [troglobit/mrouted#60]
I've just installed mrouted on Debian 12, and I have this:

# ./configure gives me these alerts:
./configure: line 4433: PKG_PROG_PKG_CONFIG: command not found
./configure: line 4699: --variable=systemdsystemunitdir: command not found

# make didn't show any alert

But:
# ./mrouted -n
mrouted: 20:06:55.221 Another multicast routing application is already running.

I don't know which other application is running multicast.... any idea?

Please help, I need to use mrouted.

Thanks. regards

**Comment by troglobit** [comment]
I'm sorry, but only you know what you have installed on your system. It could be some pim implementation, or an IGMP proxy, or smcroute? 

Also, I think you need to re-read the README so you can build the program properly.

**Comment by lucdig** [comment]
Hi, sorry, when I saw the error I located mrouted.conf in /etc, but I compiled without the options

--prefix=/usr --sysconfdir=/etc --localstatedir=/var

so the correct location of mrouted.conf is /usr/local/etc.
When I moved mrouted.conf to /usr/local/etc, I started and it worked as expected.

I built mrouted from GIT. I would like to ask: what are the steps for building new versions from GIT?
Should I purge my local directory ~/mrouted/ and "git clone" again?
Or is there any other way to avoid purging my local directory?

Thanks

**Comment by troglobit** [comment]
Please follow the [build instructions in the README](https://github.com/troglobit/mrouted#building-from-source).  I've put all the information you need there so you avoid mishaps like this.

Don't build from GIT.  There's no advantage to it at all, the [latest release](https://github.com/troglobit/mrouted/releases/latest) is the same as the latest GIT sources.  If you want to add your own features, then use a git branch, this is documented elsewhere and not something I can will help you with.
